language: c

addons:
  apt:
    packages:
      - texlive
      - texlive-math-extra
      - texlive-latex-extra

install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh

env:
  - OCAML_VERSION=4.08 PACKAGE=obelisk
  - OCAML_VERSION=4.09 PACKAGE=obelisk
  - OCAML_VERSION=4.10.0+beta1 OCAML_BETA=enable
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.11
  - OCAML_VERSION=4.12
  - OCAML_VERSION=4.13

os:
  - freebsd
  - linux
  - osx

arch:
  - amd64
  - arm64
